const MENU = {
  intern: [
    "dashboard",
    "my-tasks",
    "submissions",
    "meetings",
    "chat",
    "profile",
  ],
  team_lead: ["dashboard", "intern-tasks", "reviews", "meetings", "chat"],
  manager: ["dashboard", "analytics", "reports", "meetings", "chat"],
  admin: ["dashboard", "users", "chat", "settings"],
  // COO Panel Added Below
  coo: [
    "dashboard",
    "organization",
    "analytics",
    "meetings",
    "reports",
    "chat",
    "settings",
  ],
  cto: [
    "dashboard",
    "organization",
    "analytics",
    "reports",
    "meetings",
    "chat",
    "settings",
  ],
  cfo: [
    "dashboard",
    "organization",
    "analytics",
    "reports",
    "meetings",
    "chat",
    "settings",
  ],
  ceo: [
    "dashboard",
    "technical",
    "operations",
    "finance",
    "meetings",
    "analytics",
    "reports",
    "announcements",
    "chat",
    "settings",
  ],
};

export { MENU };
